name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: modern-saga-472703-k3
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials test-demo-cluster --zone us-central1-a --project modern-saga-472703-k3

    - name: Deploy Nginx
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/nginx-deployment

    - name: Show service
      run: kubectl get svc nginx-service -o wide
